# The peeps piss of my dog
unsetopt BEEP


DISABLE_AUTO_UPDATE="true"
DISABLE_MAGIC_FUNCTIONS="true"
DISABLE_COMPFIX="true"

# Cache completions aggressively
autoload -Uz compinit
if [ "$(date +'%j')" != "$(stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)" ]; then
    compinit
else
    compinit -C
fi

# Oh My Zsh path
export ZSH="$HOME/.oh-my-zsh"

# Theme config - fixed syntax
ZSH_THEME="spaceship"

# Spaceship settings (fixed syntax)
SPACESHIP_USER_SHOW=always
SPACESHIP_PROMPT_ASYNC=true
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_CHAR_SYMBOL="λ"
SPACESHIP_CHAR_SUFFIX=" "
# Minimal spaceship sections for performance
SPACESHIP_PROMPT_ORDER=(
  time
  user
  dir
  host
  git
  package
  node
  elixir
  erlang
  rust
  docker
  docker_compose
  line_sep
  exit_code
  char
)

# Carefully ordered plugins (syntax highlighting must be last)
plugins=(
  git
  dnf
  zsh-autosuggestions
  zsh-syntax-highlighting
)

# Source Oh My Zsh
source $ZSH/oh-my-zsh.sh

pokemon-colorscripts --no-title -s -r | fastfetch -c $HOME/.config/fastfetch/config-pokemon.jsonc --logo-type file-raw --logo-height 10 --logo-width 5 --logo -

# Autosuggest settings
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#663399,standout"
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE="20"
ZSH_AUTOSUGGEST_USE_ASYNC=1

# Alias expansion function
globalias() {
   if [[ $LBUFFER =~ '[a-zA-Z0-9]+$' ]]; then
       zle _expand_alias
       zle expand-word
   fi
   zle self-insert
}
zle -N globalias
bindkey " " globalias
bindkey "^[[Z" magic-space
bindkey -M isearch " " magic-space

# Lazy load SSH agent
function _load_ssh_agent() {
    if [ -z "$SSH_AUTH_SOCK" ]; then
        eval "$(ssh-agent -s)" > /dev/null
        ssh-add ~/.ssh/id_github_sign_and_auth 2>/dev/null
    fi
}
autoload -U add-zsh-hook
add-zsh-hook precmd _load_ssh_agent

# Path configurations
export VOLTA_HOME="$HOME/.volta"
PATH="$VOLTA_HOME/bin:$PATH:/home/locnguyen/.turso"
export PATH

export GOPATH="$HOME/.go"
export PATH="$PATH:$GOPATH/bin:$GOROOT/bin"


# Source aliases last
[ -f ~/.zsh_aliases ] && source ~/.zsh_aliases

# ---- Eza (better ls) -----
alias ls="eza --color=always --git --icons=always"

# thefuck alias
eval $(thefuck --alias)
eval $(thefuck --alias fk)

# ---- Zoxide (better cd) ----
eval "$(zoxide init zsh)"

# Other Aliases
alias cd="z"
alias vim="nvim"
alias vi="nvim"
alias listening="lsof -n -i4TCP -i4UDP"
alias kill_jupyter="procs --only pid --no-header jupyter | xargs -I '{}' kill {}"
alias activate="source .venv/bin/activate"
alias nano="echo STOP TYPING NANO"
alias ic="wezterm imgcat"
alias imgcat="wezterm imgcat"
alias zed-preview="zed --zed /Applications/Zed\ Preview.app"
alias lg="lazygit"
alias l="ledger"
alias config="git --git-dir=$HOME/.cfg --work-tree=$HOME"

# --- MISE ---
eval "$(mise activate zsh)"

# --- Stop if in non-interactive shell ---
[[ $- != *i* ]] && return


# append completions to fpath
fpath=(${ASDF_DIR}/completions $HOMEBREW_PREFIX/share/zsh/site-functions ~/.config/zsh/completions $fpath)

# -- Bindings --
bindkey "\e[1;3D" backward-word     # ⌥←
bindkey "\e[1;3C" forward-word      # ⌥→


# --- Starship ---
eval "$(starship init zsh)"
