-- AstroCommunity: import any community modules here
-- We import this file in `lazy_setup.lua` before the `plugins/` folder.
-- This guarantees that the specs are processed before any user plugins.

---@type LazySpec
return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.astro" },
  { import = "astrocommunity.pack.cpp" },
  { import = "astrocommunity.pack.docker" },
  { import = "astrocommunity.pack.elixir-phoenix" },
  { import = "astrocommunity.pack.go" },
  { import = "astrocommunity.pack.html-css" },
  { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.pack.just" },
  { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.pack.markdown" },
  { import = "astrocommunity.pack.quarto" },
  { import = "astrocommunity.pack.pkl" },
  { import = "astrocommunity.pack.rust" },
  { import = "astrocommunity.pack.svelte" },
  { import = "astrocommunity.pack.swift" },
  { import = "astrocommunity.pack.typescript" },
  { import = "astrocommunity.pack.yaml" },
  { import = "astrocommunity.code-runner.conjure" },
  { import = "astrocommunity.code-runner.molten-nvim" },
  { import = "astrocommunity.code-runner.vim-slime" },
  { import = "astrocommunity.code-runner.sniprun" },
  { import = "astrocommunity.colorscheme.catppuccin" },
  { import = "astrocommunity.colorscheme.onedarkpro-nvim" },
  { import = "astrocommunity.colorscheme.nightfox-nvim" },
  { import = "astrocommunity.colorscheme.mellifluous-nvim" },
  { import = "astrocommunity.debugging.telescope-dap-nvim" },
  { import = "astrocommunity.diagnostics.trouble-nvim" },
  { import = "astrocommunity.editing-support.nvim-treesitter-context" },
  { import = "astrocommunity.editing-support.nvim-treesitter-endwise" },
  { import = "astrocommunity.editing-support.telescope-undo-nvim" },
  { import = "astrocommunity.file-explorer.telescope-file-browser-nvim" },
  { import = "astrocommunity.file-explorer.oil-nvim" },
  { import = "astrocommunity.completion.copilot-cmp" },
  { import = "astrocommunity.completion.copilot-lua-cmp" },
  { import = "astrocommunity.completion.copilot-lua" },
  { import = "astrocommunity.markdown-and-latex.render-markdown-nvim" },
  { import = "astrocommunity.motion.nvim-surround" },
  { import = "astrocommunity.note-taking.obsidian-nvim" },
  { import = "astrocommunity.recipes.telescope-nvchad-theme" },
  { import = "astrocommunity.recipes.telescope-lsp-mappings" },
  { import = "astrocommunity.recipes.neovide" },
  { import = "astrocommunity.register.nvim-neoclip-lua" },
  { import = "astrocommunity.remote-development.distant-nvim" },
  { import = "astrocommunity.split-and-window.colorful-winsep-nvim" },
  { import = "astrocommunity.split-and-window.neominimap-nvim" },
  { import = "astrocommunity.terminal-integration.vim-tmux-navigator" },
  { import = "astrocommunity.terminal-integration.vim-tmux-yank" },
  {
    import = "astrocommunity.lsp.nvim-lint",
    opts = {
      linters_by_ft = {
        clojure = { "clj-kondo" },
        cmakefile = { "cmakelint" },
        cpp = { "clangtidy", "cppcheck", "cpplint", "flawfinder" },
        css = { "stylelint" },
        dotenv = { "dotenv_linter" },
        elixir = { "credo" },
        dockerfile = { "hadolint", "trivy" },
        haskell = { "hlint" },
        go = { "golangcilint", "revive" },
        java = { "checkstyle" },
        javascript = { "biomejs", "eslint", "jshint", "standardjs" },
        json = { "jsonlint" },
        jsx = { "biomejs" },
        kotlin = { "ktlint" },
        latex = { "chktex", "lacheck" },
        -- lua = { 'selene' },
        markdown = { "markdownlint", "vale" },
        nix = { "nix", "statix" },
        perl = { "checkpatch", "perlcritic", "perlimports" },
        php = { "php", "phpcs", "phpinsights", "phpmd", "phpstan", "psalm" },
        proto = { "buf_lint" },
        python = { "bandit", "flake8", "mypy", "pycodestyle", "pydocstyle", "pylint", "ruff", "vulture" },
        ruby = { "ruby", "rubocop", "standardrb" },
        shell = { "shellcheck" },
        sql = { "sqlfluff" },
        typescript = { "biomejs" },
        yaml = { "yamllint" },
        zsh = { "zsh" },
      },
    },
  },
  -- import/override with your plugins folder
}
