#!/usr/bin/env bash
#
## default layout (can be bsp, stack or float)
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize


# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Istats Menus$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^Jeb$" manage=off
yabai -m rule --add app="^Control Center$" manage=off
yabai -m rule --add app="^Installation Assistant$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Ghidra$" manage=off
yabai -m rule --add app="^iStats Menu$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Simulator$" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^Windows 11$" manage=off
