<<<<<<< HEAD
default-remote: local
remotes:
  alpine:
    addr: https://10.10.15.2:8443
=======
default-remote: alpine.nocsi.org
remotes:
  alpine.nocsi.org:
    addr: https://alpine.nocsi.org:8443
>>>>>>> d901fb6a429cb6b3915685da42d2e2b4d3b2d672
    auth_type: tls
    project: default
    protocol: incus
    public: false
  colima-incus:
    addr: unix:///Users/locnguyen/.colima/incus/incus.sock
    auth_type: tls
    project: default
    protocol: incus
    public: false
  docker:
    addr: https://docker.io
    protocol: oci
    public: true
  images:
    addr: https://images.linuxcontainers.org
    protocol: simplestreams
    public: true
  local:
    addr: unix://
    protocol: incus
    public: false
  nas:
    addr: https://10.10.15.4:8443
    auth_type: tls
    project: default
    protocol: incus
    public: false
aliases: {}
