[env]
TERM = "xterm-256color"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"


[window]
opacity = 0.80
dynamic_padding = false
dynamic_title = true
startup_mode = "Windowed"
decorations = "buttonless"
decorations_theme_variant = "Dark" 

[window.padding]
x = 4
y = 4

[window.position]
x = 50
y = 50

[shell]
args = ['--login']
program = "/opt/homebrew/bin/zsh"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#101010"
foreground = "#ffffff"

[colors.footer_bar.matches]
background = "CellBackground"
foreground = "#ee5396"

[colors.footer_bar]
background = "#262626"
foreground = "#ffffff"

[colors.normal]
black = "#262626"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#dde1e6"

[colors.bright]
black = "#393939"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#ffffff"

[cursor]
blink_interval = 500
style = "Beam"

[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\b"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000B"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B-"
key = "Minus"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B="
key = "Equals"
mods = "Alt"

[[mouse.bindings]]
action = "Paste"
mouse = "Middle"

[scrolling]
history = 50000
multiplier = 3
