# Live config reload (changes require restart)
live_config_reload = true

[env]
  TERM = "screen-256color"
  #TERM = "xterm-256color"
  LANG = "en_US.UTF-8"
  LC_CTYPE = "en_US.UTF-8"

[window]
  opacity = 0.70
  blur = true
  class = { instance = "alacritty", general = "alacritty" }
  dynamic_padding = true
  dynamic_title = true
  startup_mode = "Windowed"
  decorations = "buttonless"
  decorations_theme_variant = "Dark"
  option_as_alt = "Both"

[window.position]
  x = 50
  y = 50

[window.dimensions]
  columns = 80
  lines = 24

[window.padding]
  x = 10
  y = 10


[shell]
  program = "/opt/homebrew/bin/zsh"
  args = [ "--login" ]
#  args = ["-l", "-c"]

[colors]
  draw_bold_text_with_bright_colors = true

[colors.primary]
  background = "#101010"
  foreground = "#ffffff"

[colors.footer_bar]
  background = "#262626"
  foreground = "#ffffff"

[colors.normal]
  black = "#262626"
  magenta = "#ff7eb6"
  green = "#42be65"
  yellow = "#ffe97b"
  blue = "#33b1ff"
  red = "#ee5396"
  cyan = "#3ddbd9"
  white = "#dde1e6"

[colors.bright]
  black = "#393939"
  magenta = "#ff7eb6"
  green = "#42be65"
  yellow = "#ffe97b"
  blue = "#33b1ff"
  red = "#ee5396"
  cyan = "#3ddbd9"
  white = "#ffffff"

[cursor]
  style = { shape = "Block", blinking = "On" }  # Default: shape = "Block", blinking = "Off"
  vi_mode_style = "None"  # Default: "None"
  blink_interval = 750  # Default: 750
  blink_timeout = 0  # Default: 5
  unfocused_hollow = true  # Default: true
  thickness = 0.15  # Default: 0.15

############
# TERMINAL #
############

[terminal]
  osc52 = "CopyPaste"  # Default: "OnlyCopy"

#########
# MOUSE #
#########

[mouse]
  hide_when_typing = true  # Default: false

[[mouse.bindings]]
  action = "Paste"
  mouse = "Middle"


[colors.hints]
start = { foreground = "#000000", background = "#ff6600" }
end = { foreground = "#000000", background = "#ffff00" }

[hints]
enabled = [
  { regex = "(\\[[^]]*\\]\\(([^)]*)\\))|([^ ]+)|([^\\s]*[0-9]\\.[^\\s]*)|((?:https?://|git@|git://|ssh://|ftp://|file:///)\\S+)|(--- a/(\\S+))|(\\+\\+\\+ b/(\\S+))|(sha256:([0-9a-f]{64}))|((?:[.\\w\\-@~]+)?(?:/[.\\w\\-@]+)+)|(#[0-9a-fA-F]{6})|([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})|(Qm[0-9a-zA-Z]{44})|([0-9a-f]{7,40})|(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})|([A-f0-9:]+:+[A-f0-9:]+[%\\w\\d]+)|(0x[0-9a-fA-F]+)|([0-9]{4,})" , action = "Copy", binding = { key = "Space", mods = "Control|Shift" } }
]

[font]
  size = 11.0

[font.normal]
  family = "Liga SFMono Nerd Font"
  style = "Regular"

[font.bold]
  family = "Liga SFMono Nerd Font"
  style = "Bold"

[font.italic]
  family = "Liga SFMono Nerd Font"
  style = "Italic"

[font.bold_italic]
  family = "Liga SFMono Nerd Font"
  style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\b"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000B"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B-"
key = "Minus"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B="
key = "Equals"
mods = "Alt"

[selection]
save_to_clipboard = true

[scrolling]
  history = 0
  multiplier = 3
