[settings]
experimental = true

[tools]
node = "20.10.0"
go = "1.21.1"
bun = "0.7"
watchexec = "latest"
java = "openjdk-20"
maven = "3.5.4"
rust = "1.77.1"
elixir = "1.16.1"
erlang = "26.2.4"

[env]
KERL_CONFIGURE_OPTIONS = """--enable-m64-build
        --disable-debug
        --disable-hipe
        --disable-sctp
        --disable-silent-rules
        --enable-kernel-poll
        --disable-sctp
        --enable-darwin-64bit
        --enable-dynamic-ssl-lib
        --enable-dirty-schedulers
        --enable-kernel-poll
        --enable-lock-counter
        --enable-shared-zlib
        --enable-smp-support
        --enable-threads
        --enable-wx
        --with-ssl=/opt/homebrew/opt/openssl
        --with-wx-config=/opt/homebrew/bin/wx-config
        --without-javac
        --without-jinterface
        --with-dynamic-trace=dtrace
        --disable-jit
"""
CFLAGS = "-Wno-error=implicit-function-declaration -O2 -g -fno-stack-check"
CPPFLAGS = "-I/opt/homebrew/opt/llvm/include"
KERL_CONFIGURE_DISABLE_APPLICATIONS = "odbc megaco jinterface"
RUBY_CONFIGURE_OPTS = "--enable-yjit --with-openssl-dir=/opt/homebrew/opt/openssl@3 --with-readline-dir=/opt/homebrew/opt/readline --with-libyaml-dir=/opt/homebrew/opt/libyaml --with-gmp-dir=/opt/homebrew/opt/gmp"
PYTHON_CONFIGURE_OPTS = "--enable-framework --enable-optimizations --with-lto=full"
